export { matchScore } from './match-score.js'
export { keywordGapAnalysis } from './keyword-gap.js'
export { tailorResume } from './tailor-resume.js'
export { generateCoverLetter } from './cover-letter.js'
export { parseResume } from './resume-parser.js'
export { streamMockInterview, generateInterviewFeedback } from './mock-interview.js'
export type { InterviewMessage, InterviewFeedback } from './mock-interview.js'
export { generateQuestionBank } from './question-bank.js'
export type { QuestionBankResult } from './question-bank.js'
export { researchCompany } from './company-research.js'
export type { CompanyResearchResult } from './company-research.js'
export { benchmarkSalary } from './salary-benchmark.js'
export type { SalaryBenchmarkResult } from './salary-benchmark.js'
export { explainRoleFit } from './role-fit.js'
export type { RoleFitResult } from './role-fit.js'
export { formatStarStory } from './star-formatter.js'
export type { StarStoryResult } from './star-formatter.js'
export { generateFormAnswers, resolveExtensionFields, recoverExtensionField, findApplyButton } from './form-answer.js'
export type { ExtensionField, ResolvedField } from './form-answer.js'
export { openai, AI_MODEL } from './client.js'
